# Generated by Django 3.0.6 on 2020-06-01 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0002_auto_20200601_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admindetail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default='', max_length=10, null=True)),
                ('department', models.CharField(max_length=200)),
                ('product_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Product')),
            ],
        ),
    ]
