# Generated by Django 3.0.6 on 2020-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20200601_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
