# Generated by Django 3.0.6 on 2020-06-02 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0005_employeedetail_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admindetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
