# Generated by Django 3.0.6 on 2020-06-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee_id',
            new_name='employeeid',
        ),
    ]
